<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-48ME6A4" failures="1" tests="1" name="Default test" time="16.582" errors="0" timestamp="05 Oct 2024 17:13:10 GMT">
  <testcase classname="testcases.LoginTest" name="TC05_LoginFailureTest" time="7.106">
    <failure type="java.lang.AssertionError" message="expected [Please enter a valid email address] but found [The email or password you have entered is invalid.]">
      <![CDATA[java.lang.AssertionError: expected [Please enter a valid email address] but found [The email or password you have entered is invalid.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at pages.LoginPage.ValidateErrorMsg(LoginPage.java:56)
at testcases.LoginTest.TC05_LoginFailureTest(LoginTest.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC05_LoginFailureTest -->
  <testcase classname="testcases.LoginTest" name="TC01_LoginFailureTest" time="0.0">
    <ignored/>
  </testcase> <!-- TC01_LoginFailureTest -->
  <testcase classname="testcases.LoginTest" name="TC03_LoginSuccessTest" time="0.0">
    <ignored/>
  </testcase> <!-- TC03_LoginSuccessTest -->
  <testcase classname="testcases.LoginTest" name="TC02_LoginSuccessTest" time="0.0">
    <ignored/>
  </testcase> <!-- TC02_LoginSuccessTest -->
  <testcase classname="testcases.LoginTest" name="TC04_LoginSuccessTest" time="0.0">
    <ignored/>
  </testcase> <!-- TC04_LoginSuccessTest -->
</testsuite> <!-- Default test -->
